'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OmegaChallenge_2.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Ask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Ask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Correct_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Correct_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Correct_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Correct_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Correct_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Correct_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Correct_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Correct_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Finished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Finished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Ranks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Ranks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Chocobo_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Chocobo_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Ask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Ask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Correct_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Correct_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Correct_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Correct_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Correct_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Correct_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Correct_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Correct_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Finished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Finished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Ranks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Ranks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Moogle_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Moogle_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Ask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Ask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Correct_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Correct_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Correct_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Correct_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Correct_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Correct_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Correct_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Correct_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Finished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Finished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Select_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Select_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Select_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Select_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Select_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Select_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Select_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Select_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Omega_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Omega_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property OmegaSplash() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("OmegaSplash", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Ask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Ask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Correct_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Correct_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Correct_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Correct_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Correct_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Correct_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Correct_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Correct_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Finished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Finished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Ranks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Ranks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Primal_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Primal_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Moogle Test question 1,Answer A1,Answer B1,Answer C1,Answer D1,A,author 1
        '''moogle test question 2,Answer A2,Answer B2,Answer C2,Answer D2,B,author 2
        '''moogle test question3,Answer A3,Answer B3,Answer C3,Answer D3,C,author 3
        '''moogle test question 4,Answer A4,Answer B4,Answer C4,Answer D4,D,author 4
        '''moogle test question 5,Answer A5,Answer B5,Answer C5,Answer D5,A,author 5
        '''moogle test question 6,Answer A6,Answer B6,Answer C6,Answer D6,B,author 6
        '''Moogle test question 7,Answer A7,Answer B7,Answer C7,Answer D7, [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property QnA() As String
            Get
                Return ResourceManager.GetString("QnA", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Victory() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Victory", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Ask() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Ask", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Correct_A() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Correct_A", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Correct_B() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Correct_B", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Correct_C() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Correct_C", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Correct_D() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Correct_D", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Finished() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Finished", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Ranks() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Ranks", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Voidsent_Start() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Voidsent_Start", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
